version: "3.8"
services:
  backend:
    volumes:
      - ./backend:/app/medusa
      - /app/medusa/node_modules

  admin:
    volumes:
      - ./admin:/app/admin
      - /app/admin/node_modules

  storefront:
    volumes:
      - ./storefront:/app/storefront
      - /app/storefront/node_modules